# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 882eed0951e9898a2b3cfc122889d45f8c46f7ae2ddc209d20a69efd99e023706e3d5969f309a02503c97a1e4b6267a68ad60566ef374404e4d8415157b2e5bd

test:
  secret_key_base: ce0cbce31de12cccd33761353561686c3417a6c7c71ca78ebf3e005d65a96e386c8e15a47fd0123b7f2e798a50f70ee3e1f1b1b93e3d0bc5e537d6a279af4717

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
